"""Plugin implementation for Google Gemini API transcription

Docs: https://cj-mills.github.io/cjm-transcription-plugin-geminiplugin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin.ipynb.

# %% auto #0
__all__ = ['GeminiPluginConfig', 'GeminiPlugin']

# %% ../nbs/plugin.ipynb #f9a2bc9f
import json
import os
import sys
from uuid import uuid4
import logging
import tempfile
from pathlib import Path
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, Tuple, ClassVar
import re


from fastcore.basics import patch

try:
    from google import genai
    from google.genai import types
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False

try:
    from cjm_ffmpeg_utils.core import FFMPEG_AVAILABLE
    from cjm_ffmpeg_utils.audio import downsample_audio
except ImportError:
    FFMPEG_AVAILABLE = False
    
# Import domain-specific plugin interface from migrated system
from cjm_transcription_plugin_system.plugin_interface import TranscriptionPlugin
from cjm_transcription_plugin_system.core import TranscriptionResult
from cjm_transcription_plugin_system.storage import TranscriptionStorage
from cjm_plugin_system.utils.hashing import hash_file, hash_bytes
from cjm_plugin_system.core.errors import PluginInputError, PluginFatalError
# CR-12: EnvVarSpec declares the worker-env contract (the API key is a secret,
# injected into the worker env at spawn). CR-11: ConfigOption / FieldOptions
# carry the live, runtime-derived model domain.
from cjm_plugin_system.core.interface import EnvVarSpec, ConfigOption, FieldOptions
from cjm_plugin_system.utils.validation import (
    dict_to_config, config_to_dict, validate_config, dataclass_to_jsonschema,
    SCHEMA_TITLE, SCHEMA_DESC, SCHEMA_MIN, SCHEMA_MAX, SCHEMA_ENUM
)

from cjm_transcription_plugin_gemini.meta import (
    get_plugin_metadata
)

# %% ../nbs/plugin.ipynb #adc2fb86-7489-41e2-9018-4d434ef6bdb7
@dataclass
class GeminiPluginConfig:
    """Configuration for Gemini transcription plugin.

    CR-11/CR-12 notes:
      - `model` has NO static enum and NO default. Its valid domain is the live
        Gemini model list, surfaced at runtime via `get_config_options()` — a
        baked-in enum/default goes stale (models are retired/added server-side),
        and if the live list can't be fetched the API is unusable anyway, so a
        default selection is worthless. `model` is None until the operator picks
        one from the live list.
      - The API key is NOT a config field. It is a secret declared in
        `GeminiPlugin.WORKER_ENV` and resolved from the SecretStore into the
        worker env at spawn (see CR-12).
    """
    model:Optional[str] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Model",
            SCHEMA_DESC: "Gemini model for transcription. Domain is runtime-derived from the live API model list (get_config_options); no static default."
        }
    )
    prompt:str = field(
        default="Generate a transcription of the audio, only extract speech and ignore background audio.",
        metadata={
            SCHEMA_TITLE: "Prompt",
            SCHEMA_DESC: "Prompt for transcription"
        }
    )
    temperature:float = field(
        default=0.0,
        metadata={
            SCHEMA_TITLE: "Temperature",
            SCHEMA_DESC: "Sampling temperature",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 2.0
        }
    )
    top_p:float = field(
        default=0.95,
        metadata={
            SCHEMA_TITLE: "Top P",
            SCHEMA_DESC: "Top-p sampling parameter",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 1.0
        }
    )
    max_output_tokens:int = field(
        default=65536,
        metadata={
            SCHEMA_TITLE: "Max Output Tokens",
            SCHEMA_DESC: "Maximum number of output tokens (per-model ceiling surfaced as a live constraint via get_config_options)",
            SCHEMA_MIN: 1,
            SCHEMA_MAX: 65536
        }
    )
    seed:Optional[int] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Seed",
            SCHEMA_DESC: "Random seed for reproducibility"
        }
    )
    response_mime_type:str = field(
        default="text/plain",
        metadata={
            SCHEMA_TITLE: "Response MIME Type",
            SCHEMA_DESC: "Response MIME type",
            SCHEMA_ENUM: ["text/plain", "application/json"]
        }
    )
    downsample_audio:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Downsample Audio",
            SCHEMA_DESC: "Downsample audio before uploading (requires ffmpeg)"
        }
    )
    downsample_rate:int = field(
        default=16000,
        metadata={
            SCHEMA_TITLE: "Downsample Rate",
            SCHEMA_DESC: "Target sample rate for downsampling",
            SCHEMA_ENUM: [8000, 16000, 22050, 44100]
        }
    )
    downsample_channels:int = field(
        default=1,
        metadata={
            SCHEMA_TITLE: "Downsample Channels",
            SCHEMA_DESC: "Number of audio channels (1=mono, 2=stereo)",
            SCHEMA_ENUM: [1, 2]
        }
    )
    safety_settings:str = field(
        default="OFF",
        metadata={
            SCHEMA_TITLE: "Safety Settings",
            SCHEMA_DESC: "Safety filter threshold",
            SCHEMA_ENUM: ["OFF", "BLOCK_NONE", "BLOCK_FEW", "BLOCK_SOME", "BLOCK_MOST"]
        }
    )
    model_filter:List[str] = field(
        default_factory=list,
        metadata={
            SCHEMA_TITLE: "Model Filter",
            SCHEMA_DESC: "Keywords to exclude from the live model list (e.g., ['tts', 'image'])"
        }
    )
    use_file_upload:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Use File Upload",
            SCHEMA_DESC: "Upload audio files to Gemini API instead of embedding in request"
        }
    )
    use_streaming:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Use Streaming",
            SCHEMA_DESC: "Use streaming response for transcription"
        }
    )
    delete_uploaded_files:bool = field(
        default=True,
        metadata={
            SCHEMA_TITLE: "Delete Uploaded Files",
            SCHEMA_DESC: "Delete uploaded files after transcription"
        }
    )

# %% ../nbs/plugin.ipynb #fcfcb260-d962-49ae-8bb9-d521a723f201
class GeminiPlugin(TranscriptionPlugin):
    """Google Gemini API transcription plugin."""
    
    config_class = GeminiPluginConfig

    # CR-12: the worker-environment contract. The API key is a SECRET resolved
    # from the SecretStore (keyed by plugin name, so multiple instances share
    # one key) and injected into the worker env at spawn — never a config field,
    # never persisted in config / logged. Set it via
    #   cjm-ctl set-secret cjm-transcription-plugin-gemini GEMINI_API_KEY
    # or PluginManager.set_plugin_secret(...). Changing it respawns the worker.
    WORKER_ENV: ClassVar[List[EnvVarSpec]] = [
        EnvVarSpec(
            name="GEMINI_API_KEY",
            secret=True,
            required=True,
            label="Gemini API Key",
            description="Google Gemini API key used to authenticate the worker (read from the worker env at spawn).",
        ),
    ]
    
    def __init__(self):
        """Initialize the Gemini plugin with default configuration."""
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config: GeminiPluginConfig = None
        self.client = None
        self.available_models = []
        self.model_token_limits = {}  # model name -> output_token_limit (populated from the live API)
        self.uploaded_files = []  # Track uploaded files for cleanup
        self.storage: Optional[TranscriptionStorage] = None
    
    @property
    def name(self) -> str: # Plugin name identifier
        """Return the plugin name identifier."""
        return "gemini"
    
    @property
    def version(self) -> str: # Plugin version string
        """Return the plugin version string."""
        return "1.0.0"
    
    @property
    def supported_formats(self) -> List[str]: # List of supported audio formats
        """Return list of supported audio file formats."""
        return ["wav", "mp3", "aiff", "aac", "ogg", "flac"]

    def get_current_config(self) -> Dict[str, Any]: # Current configuration as dictionary
        """Return current configuration state."""
        if not self.config:
            return {}
        return config_to_dict(self.config)

    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema for configuration
        """Return JSON Schema for UI generation."""
        return dataclass_to_jsonschema(GeminiPluginConfig)

    @staticmethod
    def get_config_dataclass() -> GeminiPluginConfig: # Configuration dataclass
        """Return dataclass describing the plugin's configuration options."""
        return GeminiPluginConfig
    
    def initialize(
        self,
        config: Optional[Any] = None # Configuration dataclass, dict, or None
    ) -> None:
        """First-time setup (CR-4): apply config + set up storage.

        Does NOT eagerly create the API client or fetch the model list — the
        client is created lazily (see `_ensure_client`) once the GEMINI_API_KEY
        is present in the worker env. This lets the plugin LOAD without a key
        (so a config UI can collect one post-load), and means the live model
        list (`get_config_options`) only populates once the key is set + the
        worker has respawned with it injected.
        """
        self._apply_config(config)

    def _apply_config(
        self,
        config: Optional[Any] = None # Configuration dataclass, dict, or None
    ) -> None:
        """CR-4 seam: (re)apply configuration without recreating the client.

        The substrate's `reconfigure(old, new)` path calls this after firing any
        RELOAD_TRIGGER releases. Gemini has no RELOAD_TRIGGER config fields — the
        client depends only on the spawn-injected API key, and `model` / prompt /
        sampling params are per-request — so reconfigure is a pure config-swap
        (no client churn). The API key itself changes via a worker RESPAWN
        (set_plugin_secret), not through here.
        """
        new_config = dict_to_config(GeminiPluginConfig, config or {})
        self.config = new_config

        # Standardized storage (idempotent; cheap to re-open).
        db_path = get_plugin_metadata()["db_path"]
        self.storage = TranscriptionStorage(db_path)

        # Clamp max_output_tokens to the selected model's live ceiling when known
        # (model_token_limits is populated lazily once the client has listed models).
        if self.config.model:
            self._update_max_tokens_for_model(self.config.model)

        self.logger.info(f"Gemini plugin configured (model={self.config.model!r})")

    def _ensure_client(self) -> None:
        """Lazily create the genai client from the spawn-injected GEMINI_API_KEY.

        Tolerant by design: if the key is absent the client stays None and the
        caller decides what to do (execute raises a typed error; get_config_options
        returns {} so the UI falls back to 'set a key first'). The key is read
        from the worker env — provenance is the SecretStore (CR-12), injected at
        spawn; a key change arrives via a worker respawn, so reading os.environ
        here always reflects the current injected value.
        """
        if self.client is not None:
            return
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            return
        self.client = genai.Client(api_key=api_key)

    def execute(
        self,
        audio: Union[str, Path], # Audio data object or path to audio file
        **kwargs # Additional arguments to override config
    ) -> TranscriptionResult: # Transcription result object
        """Transcribe audio using Gemini."""
        self._ensure_client()
        if not self.client:
            raise PluginFatalError(  # CR-12: no API key injected — operator must set the secret
                "No GEMINI_API_KEY in the worker environment. Set it via "
                "`cjm-ctl set-secret cjm-transcription-plugin-gemini GEMINI_API_KEY` "
                "(or PluginManager.set_plugin_secret), which respawns the worker with the key."
            )

        # CR-11: model has no static default — a model must be selected (from the
        # live list) before transcription. Allow a per-call override via kwargs.
        model = kwargs.get("model", self.config.model)
        if not model:
            raise PluginInputError(
                "No Gemini model selected. Choose one from the live model list "
                "(get_config_options) and set it in the plugin config.",
                fields_invalid=["model"],
            )
        # If a model is overridden at execution time, refresh its token ceiling.
        if "model" in kwargs and kwargs["model"] != self.config.model:
            self._update_max_tokens_for_model(kwargs["model"])
        
        # Prepare audio file
        audio_path, temp_created = self._prepare_audio(audio)
        uploaded_file = None
        
        # Hash the audio file before transcription
        audio_hash = hash_file(str(audio_path))
        
        try:
            # Get config values, allowing kwargs overrides
            temperature = kwargs.get("temperature", self.config.temperature)
            top_p = kwargs.get("top_p", self.config.top_p)
            max_output_tokens = kwargs.get("max_output_tokens", self.config.max_output_tokens)
            seed = kwargs.get("seed", self.config.seed)
            response_mime_type = kwargs.get("response_mime_type", self.config.response_mime_type)
            safety_settings = kwargs.get("safety_settings", self.config.safety_settings)
            prompt = kwargs.get("prompt", self.config.prompt)
            use_file_upload = kwargs.get("use_file_upload", self.config.use_file_upload)
            use_streaming = kwargs.get("use_streaming", self.config.use_streaming)
            delete_uploaded_files = kwargs.get("delete_uploaded_files", self.config.delete_uploaded_files)
            
            # Decide whether to upload file or embed in request
            if use_file_upload:
                # Upload audio file to Gemini API
                uploaded_file = self._upload_audio_file(audio_path)
                audio_content = uploaded_file
            else:
                # Read audio file and embed in request (existing behavior)
                with open(audio_path, 'rb') as f:
                    audio_bytes = f.read()
                
                # Determine MIME type
                suffix = audio_path.suffix.lower()
                mime_map = {
                    '.wav': 'audio/wav',
                    '.mp3': 'audio/mp3',
                    '.aiff': 'audio/aiff',
                    '.aac': 'audio/aac',
                    '.ogg': 'audio/ogg',
                    '.flac': 'audio/flac'
                }
                mime_type = mime_map.get(suffix, 'audio/wav')
                
                # Create audio content part
                audio_content = types.Part.from_bytes(
                    data=audio_bytes,
                    mime_type=mime_type
                )
            
            # Prepare generation config
            generate_config = types.GenerateContentConfig(
                response_mime_type=response_mime_type,
                temperature=temperature,
                top_p=top_p,
                max_output_tokens=max_output_tokens,
                seed=seed,
                safety_settings=[
                    types.SafetySetting(
                        category="HARM_CATEGORY_HATE_SPEECH",
                        threshold=safety_settings
                    ),
                    types.SafetySetting(
                        category="HARM_CATEGORY_DANGEROUS_CONTENT",
                        threshold=safety_settings
                    ),
                    types.SafetySetting(
                        category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                        threshold=safety_settings
                    ),
                    types.SafetySetting(
                        category="HARM_CATEGORY_HARASSMENT",
                        threshold=safety_settings
                    )
                ]
            )
            
            # Prepare contents
            contents = [prompt, audio_content]
            
            # Generate transcription
            self.logger.info(f"Transcribing with Gemini model: {model} (max_tokens: {max_output_tokens})")
            
            # Use streaming or regular generation
            if use_streaming:
                # Use streaming response
                transcribed_text = ""
                for chunk in self.client.models.generate_content_stream(
                    model=model,
                    contents=contents,
                    config=generate_config
                ):
                    if hasattr(chunk, 'text'):
                        transcribed_text += chunk.text
                self.logger.info("Streaming transcription completed")
            else:
                # Use regular response (existing behavior)
                response = self.client.models.generate_content(
                    model=model,
                    contents=contents,
                    config=generate_config
                )
                transcribed_text = response.text if hasattr(response, 'text') else str(response)

            # Capture provenance metadata passed via kwargs
            provenance_meta = {
                k: v for k, v in kwargs.items() 
                if k in ['source_start_time', 'source_end_time']
            }
            
            # Create result
            result = TranscriptionResult(
                text=transcribed_text.strip(),
                confidence=None,  # Gemini doesn't provide confidence scores
                segments=None,  # Gemini doesn't provide segments by default
                metadata={
                    "model": model,
                    **provenance_meta,
                    "temperature": temperature,
                    "top_p": top_p,
                    "max_output_tokens": max_output_tokens,
                    "prompt": prompt,
                    "use_file_upload": use_file_upload,
                    "use_streaming": use_streaming
                }
            )
            
            # Hash the transcription output
            text_hash = hash_bytes(result.text.encode())
            
            # Save to standardized storage (helper logs success/failure; never raises)
            job_id = kwargs.get("job_id", str(uuid4()))
            self.storage.save_with_logging(
                job_id=job_id,
                audio_path=str(audio),
                audio_hash=audio_hash,
                text=result.text,
                text_hash=text_hash,
                segments=result.segments,
                metadata=result.metadata,
                logger=self.logger,
            )
            
            self.logger.info(f"Transcription completed: {len(transcribed_text.split())} words")
            return result
            
        finally:
            # Clean up uploaded file if configured to do so
            if uploaded_file and delete_uploaded_files:
                try:
                    self._delete_uploaded_file(uploaded_file.name)
                    # Remove from tracking list
                    self.uploaded_files = [f for f in self.uploaded_files if f.name != uploaded_file.name]
                except Exception as e:
                    self.logger.warning(f"Failed to cleanup uploaded file: {e}")
            
            # Clean up temporary file
            if temp_created:
                try:
                    audio_path.unlink()
                except Exception:
                    pass

    def is_available(self) -> bool: # True if the Gemini API is available
        """Check if Gemini API is available."""
        return GEMINI_AVAILABLE

    def get_config_options(self) -> Dict[str, "FieldOptions"]:
        """CR-11: live config option domains, keyed by config field name.

        Surfaces the live Gemini model list for `model` (with per-model output
        token limits as option metadata + a derived `max_output_tokens` ceiling
        constraint for the currently-selected model). Returns {} when no client
        is available (no API key yet) or the API can't be reached — there is no
        useful static fallback (a stale model list is worse than none), so the
        UI shows 'set an API key first' rather than a frozen enum.
        """
        self._ensure_client()
        if self.client is None:
            return {}
        models = self._refresh_available_models()
        if not models:
            return {}
        options = [
            ConfigOption(
                value=m,
                label=m,
                metadata={"output_token_limit": self.model_token_limits.get(m)},
            )
            for m in models
        ]
        constraints: Dict[str, Any] = {}
        current = self.config.model if self.config else None
        if current and current in self.model_token_limits:
            # Live per-model ceiling for max_output_tokens (CR-11 derived constraint).
            constraints["max_output_tokens"] = {"maximum": self.model_token_limits[current]}
        return {"model": FieldOptions(options=options, constraints=constraints)}

    def prefetch(self) -> None:
        """CR-4: eagerly create the client + warm the live model list.

        Optional pre-warm so the first get_config_options / execute is fast.
        No-op (client stays None) when no API key is injected yet.
        """
        self._ensure_client()
        if self.client is not None:
            self.available_models = self._refresh_available_models()

    def on_disable(self) -> None:
        """CR-2: release the API client when the operator disables the plugin.

        Lightweight for an API plugin (no GPU/model memory), but drops the client
        so a re-enable / next execute lazily re-creates it from the current env.
        """
        self.client = None

    def cleanup(
        self
    ) -> None:
        """Clean up resources."""
        # Clean up any remaining uploaded files
        if self.config and self.config.delete_uploaded_files:
            for uploaded_file in self.uploaded_files:
                try:
                    self._delete_uploaded_file(uploaded_file.name)
                except Exception as e:
                    self.logger.warning(f"Failed to delete file during cleanup: {e}")
        
        self.uploaded_files = []
        self.client = None
        self.logger.info("Cleanup completed")

# %% ../nbs/plugin.ipynb #54a46385-4987-4ead-9be7-f0ef0e49e3cc
from dataclasses import replace as dataclass_replace

@patch
def _refresh_available_models(
    self:GeminiPlugin
) -> List[str]:  # Live audio-capable model names (empty if no client / API unreachable)
    """Fetch + filter audio-capable models from the LIVE Gemini API (CR-11).

    Returns [] when there's no client or the API can't be reached — there is no
    static fallback list (a stale model list is worse than none; a baked default
    rots as Google retires/adds models). Side effect: repopulates
    self.model_token_limits (model name -> output_token_limit) for the live set.
    """
    if not self.client:
        return []
    try:
        all_models = list(self.client.models.list())
        gen_models = [m for m in all_models if 'generateContent' in m.supported_actions]

        # Default filter excludes non-transcription model families.
        model_filter = self.config.model_filter if (self.config and self.config.model_filter) else ['tts', 'image', 'learn']

        filtered_names = []
        self.model_token_limits = {}  # Reset; repopulate from the live set
        for model in gen_models:
            model_name = model.name.removeprefix('models/')
            if not any(keyword in model_name.lower() for keyword in model_filter):
                filtered_names.append(model_name)
                self.model_token_limits[model_name] = model.output_token_limit

        filtered_names.sort(reverse=True)  # newest/best first
        self.logger.info(f"Found {len(filtered_names)} audio-capable models")
        return filtered_names
    except Exception as e:
        self.logger.warning(f"Could not fetch models from the Gemini API: {e}")
        return []

@patch
def _update_max_tokens_for_model(
    self:GeminiPlugin,
    model_name: str  # Model name to update tokens for
) -> None:
    """Clamp max_output_tokens to the model's live output_token_limit when known."""
    if model_name in self.model_token_limits:
        token_limit = self.model_token_limits[model_name]
        self.config = dataclass_replace(self.config, max_output_tokens=token_limit)
        self.logger.info(f"Updated max_output_tokens to {token_limit} for model '{model_name}'")
    else:
        # Unknown until the live list is fetched; keep a sensible numeric default.
        default_limit = 65536
        self.config = dataclass_replace(self.config, max_output_tokens=default_limit)
        self.logger.info(f"Using default max_output_tokens of {default_limit} for model '{model_name}'")

# %% ../nbs/plugin.ipynb #f3e50ea0-61eb-42bf-a4e5-3e6780a97b6d
@patch
def update_config(
    self:GeminiPlugin,
    config: Union[Dict[str, Any], GeminiPluginConfig]  # New configuration values
) -> None:
    """Update plugin configuration, adjusting max_tokens if model changes."""
    old_model = self.config.model if self.config else None
    
    # Handle different input types
    if isinstance(config, dict):
        # Merge with existing config using replace
        self.config = dataclass_replace(self.config, **config)
    elif isinstance(config, GeminiPluginConfig):
        self.config = config
    else:
        raise PluginInputError(  # SG-47: caller passed wrong config shape
        f"Expected dict or GeminiPluginConfig, got {type(config).__name__}", fields_invalid=["config"],
    )
    
    # If model changed, update max_output_tokens
    if self.config.model and self.config.model != old_model:
        self._update_max_tokens_for_model(self.config.model)

@patch
def _prepare_audio(
    self:GeminiPlugin,
    audio: Union[str, Path]  # Path to a decodable audio file
) -> Tuple[Path, bool]:  # Tuple of (processed audio path, whether temp file was created)
    """Prepare audio file for upload.

    The caller provides a decodable audio file path; in-memory preparation is no
    longer a plugin responsibility. Optional downsampling (a relocation candidate
    that belongs in an upstream ffmpeg pipeline step) is retained for now."""
    temp_created = False

    if isinstance(audio, (str, Path)):
        audio_path = Path(audio)
    else:
        raise PluginInputError(  # SG-47: typed input-validation
            f"Unsupported audio input type: {type(audio)}; expected a file path (str or Path)",
            fields_invalid=["audio"],
        )

    # Optionally downsample audio
    if self.config.downsample_audio and FFMPEG_AVAILABLE:
        try:
            downsampled = audio_path.with_stem(f"{audio_path.stem}_downsampled")
            downsample_audio(
                audio_path,
                downsampled,
                sample_rate=self.config.downsample_rate,
                channels=self.config.downsample_channels
            )

            # Clean up original temp file if created
            if temp_created:
                audio_path.unlink()

            audio_path = downsampled
            temp_created = True
            self.logger.info(f"Downsampled audio to {self.config.downsample_rate}Hz")

        except Exception as e:
            self.logger.warning(f"Failed to downsample audio: {e}")

    return audio_path, temp_created

@patch
def _upload_audio_file(
    self:GeminiPlugin,
    audio_path: Path  # Path to audio file to upload
) -> Any:  # Uploaded file object
    """Upload audio file to Gemini API."""
    try:
        self.logger.info(f"Uploading audio file: {audio_path}")
        uploaded_file = self.client.files.upload(file=audio_path)
        self.uploaded_files.append(uploaded_file)  # Track for cleanup
        self.logger.info(f"Successfully uploaded file: {uploaded_file.name}")
        return uploaded_file
    except Exception as e:
        self.logger.error(f"Failed to upload audio file: {e}")
        raise

@patch
def _delete_uploaded_file(
    self:GeminiPlugin,
    file_name: str  # Name of file to delete
) -> None:
    """Delete an uploaded file from Gemini API."""
    try:
        self.client.files.delete(name=file_name)
        self.logger.info(f"Deleted uploaded file: {file_name}")
    except Exception as e:
        self.logger.warning(f"Failed to delete uploaded file {file_name}: {e}")

# %% ../nbs/plugin.ipynb #5e0932b0
@patch
def get_available_models(
    self:GeminiPlugin
) -> List[str]:  # Live audio-capable model names (empty if no API key / API unreachable)
    """Get the live list of audio-capable models (CR-11).

    Lazily ensures the client from the injected API key, then refreshes from the
    API. Returns [] when no key is available — no static fallback.
    """
    self._ensure_client()
    if self.client:
        self.available_models = self._refresh_available_models()
    return self.available_models

@patch
def get_model_info(
    self:GeminiPlugin,
    model_name: Optional[str] = None  # Model name to get info for, defaults to current model
) -> Dict[str, Any]:  # Dict with model information
    """Get information about a specific model including its token limit."""
    if model_name is None:
        model_name = self.config.model if self.config else None
    return {
        "name": model_name,
        "output_token_limit": (self.model_token_limits.get(model_name, 65536) if model_name else None),
        "current_max_output_tokens": self.config.max_output_tokens if self.config else 65536
    }

# %% ../nbs/plugin.ipynb #odr8y9xm0z
from typing import Generator

@patch
def supports_streaming(
    self:GeminiPlugin
) -> bool:  # True if streaming is supported
    """Check if this plugin supports streaming transcription."""
    return True

@patch  
def execute_stream(
    self:GeminiPlugin,
    audio: Union[str, Path],  # Audio data object or path to audio file
    **kwargs  # Additional arguments to override config
) -> Generator[str, None, TranscriptionResult]:  # Yields text chunks, returns final result
    """Stream transcription results chunk by chunk."""
    self._ensure_client()
    if not self.client:
        raise PluginFatalError(  # CR-12: no API key injected
            "No GEMINI_API_KEY in the worker environment. Set it via "
            "`cjm-ctl set-secret cjm-transcription-plugin-gemini GEMINI_API_KEY`."
        )

    # Force streaming mode in config
    kwargs['use_streaming'] = True

    # CR-11: a model must be selected (from the live list).
    if not kwargs.get("model", self.config.model):
        raise PluginInputError(
            "No Gemini model selected. Choose one from the live model list.",
            fields_invalid=["model"],
        )
    # Check if model is being overridden at execution time
    if "model" in kwargs and kwargs["model"] != self.config.model:
        self._update_max_tokens_for_model(kwargs["model"])
    
    # Prepare audio file
    audio_path, temp_created = self._prepare_audio(audio)
    uploaded_file = None
    
    try:
        # Get config values, allowing kwargs overrides
        model = kwargs.get("model", self.config.model)
        temperature = kwargs.get("temperature", self.config.temperature)
        top_p = kwargs.get("top_p", self.config.top_p)
        max_output_tokens = kwargs.get("max_output_tokens", self.config.max_output_tokens)
        seed = kwargs.get("seed", self.config.seed)
        response_mime_type = kwargs.get("response_mime_type", self.config.response_mime_type)
        safety_settings = kwargs.get("safety_settings", self.config.safety_settings)
        prompt = kwargs.get("prompt", self.config.prompt)
        use_file_upload = kwargs.get("use_file_upload", self.config.use_file_upload)
        delete_uploaded_files = kwargs.get("delete_uploaded_files", self.config.delete_uploaded_files)
        
        # Decide whether to upload file or embed in request
        if use_file_upload:
            # Upload audio file to Gemini API
            uploaded_file = self._upload_audio_file(audio_path)
            audio_content = uploaded_file
        else:
            # Read audio file and embed in request
            with open(audio_path, 'rb') as f:
                audio_bytes = f.read()
            
            # Determine MIME type
            suffix = audio_path.suffix.lower()
            mime_map = {
                '.wav': 'audio/wav',
                '.mp3': 'audio/mp3',
                '.aiff': 'audio/aiff',
                '.aac': 'audio/aac',
                '.ogg': 'audio/ogg',
                '.flac': 'audio/flac'
            }
            mime_type = mime_map.get(suffix, 'audio/wav')
            
            # Create audio content part
            audio_content = types.Part.from_bytes(
                data=audio_bytes,
                mime_type=mime_type
            )
        
        # Prepare generation config
        generate_config = types.GenerateContentConfig(
            response_mime_type=response_mime_type,
            temperature=temperature,
            top_p=top_p,
            max_output_tokens=max_output_tokens,
            seed=seed,
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_HATE_SPEECH",
                    threshold=safety_settings
                ),
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold=safety_settings
                ),
                types.SafetySetting(
                    category="HARM_CATEGORY_SEXUALLY_EXPLICIT",
                    threshold=safety_settings
                ),
                types.SafetySetting(
                    category="HARM_CATEGORY_HARASSMENT",
                    threshold=safety_settings
                )
            ]
        )
        
        # Prepare contents
        contents = [prompt, audio_content]
        
        # Generate transcription with streaming
        self.logger.info(f"Streaming transcription with Gemini model: {model} (max_tokens: {max_output_tokens})")
        
        transcribed_text = ""
        chunks_yielded = 0
        
        # Stream chunks as they arrive
        for chunk in self.client.models.generate_content_stream(
            model=model,
            contents=contents,
            config=generate_config
        ):
            if hasattr(chunk, 'text'):
                chunk_text = chunk.text
                transcribed_text += chunk_text
                chunks_yielded += 1
                yield chunk_text  # Yield each chunk in real-time
        
        self.logger.info(f"Streaming completed: {chunks_yielded} chunks, {len(transcribed_text.split())} words")
        
        # Return final result
        return TranscriptionResult(
            text=transcribed_text.strip(),
            confidence=None,  # Gemini doesn't provide confidence scores
            segments=None,  # Gemini doesn't provide segments by default
            metadata={
                "model": model,
                "temperature": temperature,
                "top_p": top_p,
                "max_output_tokens": max_output_tokens,
                "prompt": prompt[:100] + "..." if len(prompt) > 100 else prompt,
                "use_file_upload": use_file_upload,
                "use_streaming": True,
                "streaming_chunks": chunks_yielded
            }
        )
        
    finally:
        # Clean up uploaded file if configured to do so
        if uploaded_file and delete_uploaded_files:
            try:
                self._delete_uploaded_file(uploaded_file.name)
                # Remove from tracking list
                self.uploaded_files = [f for f in self.uploaded_files if f.name != uploaded_file.name]
            except Exception as e:
                self.logger.warning(f"Failed to cleanup uploaded file: {e}")
        
        # Clean up temporary file
        if temp_created:
            try:
                audio_path.unlink()
            except Exception:
                pass
